### ISSUE TITLE
Ecto type warnings

### ISSUE THREAD

**Issue by glennr** [vforgione/pg_ranges#3]
ecto: 3.4.4
pg_ranges: 0.1.0

```
==> pg_ranges
Compiling 7 files (.ex)
warning: function embed_as/1 required by behaviour Ecto.Type is not implemented (in module PgRanges.DateRange)
  lib/pg_ranges/daterange.ex:1: PgRanges.DateRange (module)

warning: function embed_as/1 required by behaviour Ecto.Type is not implemented (in module PgRanges.Int8Range)
  lib/pg_ranges/int8range.ex:1: PgRanges.Int8Range (module)

warning: function embed_as/1 required by behaviour Ecto.Type is not implemented (in module PgRanges.NumRange)
  lib/pg_ranges/numrange.ex:1: PgRanges.NumRange (module)

warning: function embed_as/1 required by behaviour Ecto.Type is not implemented (in module PgRanges.TstzRange)
  lib/pg_ranges/tstzrange.ex:1: PgRanges.TstzRange (module)

warning: function embed_as/1 required by behaviour Ecto.Type is not implemented (in module PgRanges.Int4Range)
  lib/pg_ranges/int4range.ex:1: PgRanges.Int4Range (module)

warning: function embed_as/1 required by behaviour Ecto.Type is not implemented (in module PgRanges.TsRange)
  lib/pg_ranges/tsrange.ex:1: PgRanges.TsRange (module)

warning: function equal?/2 required by behaviour Ecto.Type is not implemented (in module PgRanges.DateRange)
  lib/pg_ranges/daterange.ex:1: PgRanges.DateRange (module)

warning: function equal?/2 required by behaviour Ecto.Type is not implemented (in module PgRanges.Int8Range)
  lib/pg_ranges/int8range.ex:1: PgRanges.Int8Range (module)

warning: function equal?/2 required by behaviour Ecto.Type is not implemented (in module PgRanges.NumRange)
  lib/pg_ranges/numrange.ex:1: PgRanges.NumRange (module)

warning: function equal?/2 required by behaviour Ecto.Type is not implemented (in module PgRanges.TstzRange)
  lib/pg_ranges/tstzrange.ex:1: PgRanges.TstzRange (module)

warning: function equal?/2 required by behaviour Ecto.Type is not implemented (in module PgRanges.Int4Range)
  lib/pg_ranges/int4range.ex:1: PgRanges.Int4Range (module)

warning: function equal?/2 required by behaviour Ecto.Type is not implemented (in module PgRanges.TsRange)
  lib/pg_ranges/tsrange.ex:1: PgRanges.TsRange (module)
```

**Comment by glennr** [comment]
No longer a warning, but an error it appears.

Elixir 1.11
Phx: 1.5.5
Ecto 3.5.1
Pg-ranges: 0.1.0


```
 ** (UndefinedFunctionError) function PgRanges.DateRange.equal?/2 is undefined or private, but the behaviour Ecto.Type expects it to be present
     stacktrace:
       (pg_ranges 0.1.0) PgRanges.DateRange.equal?(nil, %PgRanges.DateRange{r: %Postgrex.Range{lower: ~D[2020-10-19], lower_inclusive: true, upper: ~D[2020-10-25], upper_inclusive: false}})
       (ecto 3.5.1) lib/ecto/changeset.ex:564: Ecto.Changeset.cast_field/8
       (ecto 3.5.1) lib/ecto/changeset.ex:523: Ecto.Changeset.process_param/7
       (elixir 1.11.0) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto 3.5.1) lib/ecto/changeset.ex:501: Ecto.Changeset.cast/6
```

Same issue as this perhaps: https://github.com/TheRealReal/ecto-ulid/pull/7

**Comment by vforgione** [comment]
Seems to be fixed in latest. Please check.
